obstacle_range: 2.0
raytrace_range: 3.0
footprint: [[0.2, 0.2], [0.2, -0.2], [-0.2, 0.2], [-0.2, -0.2]]
#robot_radius: 0.20 #ir_of_robot
inflation_radiuscans: 0.50

observation_sources: laser_scan_sensor #point_cloud_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: camera, data_type: PointCloud, topic: /camera/depth/points, marking: true, clearing: true}
